# Generated by Django 6.0.3 on 2026-05-02 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to update field metadata.
    Adds descriptive 'verbose_name' attributes to all models (KanbanTask, ProjectBoard, TaskNote)
    to improve readability in the Django Admin interface.
    """

    # Linking to the previous initial migration
    dependencies = [
        ('kanban_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # --- Updates for KanbanTask Fields ---
        migrations.AlterField(
            model_name='kanbantask',
            name='current_status',
            field=models.CharField(choices=[('bk', 'Backlog'), ('dg', 'In Arbeit'), ('ts', 'Qualitätskontrolle'), ('cp', 'Abgeschlossen')], default='bk', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='kanbantask',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fälligkeitsdatum'),
        ),
        migrations.AlterField(
            model_name='kanbantask',
            name='info_text',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='kanbantask',
            name='label',
            field=models.CharField(max_length=200, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='kanbantask',
            name='parent_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_tasks', to='kanban_app.projectboard', verbose_name='Zugehöriges Board'),
        ),
        migrations.AlterField(
            model_name='kanbantask',
            name='priority_level',
            field=models.IntegerField(choices=[(1, 'Niedrig'), (2, 'Normal'), (3, 'Hoch'), (4, 'Kritisch')], default=2, verbose_name='Priorität'),
        ),
        migrations.AlterField(
            model_name='kanbantask',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_to_check', to=settings.AUTH_USER_MODEL, verbose_name='Prüfer'),
        ),
        migrations.AlterField(
            model_name='kanbantask',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_todo', to=settings.AUTH_USER_MODEL, verbose_name='Bearbeiter'),
        ),

        # --- Updates for ProjectBoard Fields ---
        migrations.AlterField(
            model_name='projectboard',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Ersteller'),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Projektname'),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='participants',
            field=models.ManyToManyField(related_name='joined_projects', to=settings.AUTH_USER_MODEL, verbose_name='Mitglieder'),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='summary',
            field=models.TextField(blank=True, max_length=400, verbose_name='Zusammenfassung'),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),

        # --- Updates for TaskNote Fields ---
        migrations.AlterField(
            model_name='tasknote',
            name='message',
            field=models.TextField(verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='tasknote',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Gepostet am'),
        ),
        migrations.AlterField(
            model_name='tasknote',
            name='target_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='kanban_app.kanbantask', verbose_name='Ziel-Aufgabe'),
        ),
        migrations.AlterField(
            model_name='tasknote',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_notes', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]