# Generated by Django 6.0.3 on 2026-04-29 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('summary', models.TextField(blank=True, max_length=400)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='joined_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KanbanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('info_text', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('bk', 'Backlog'), ('dg', 'In Arbeit'), ('ts', 'Qualitätskontrolle'), ('cp', 'Abgeschlossen')], default='bk', max_length=2)),
                ('priority_level', models.IntegerField(choices=[(1, 'Niedrig'), (2, 'Normal'), (3, 'Hoch'), (4, 'Kritisch')], default=2)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_to_check', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_todo', to=settings.AUTH_USER_MODEL)),
                ('parent_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_tasks', to='KanMind_Backend.projectboard')),
            ],
        ),
        migrations.CreateModel(
            name='TaskNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('target_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='KanMind_Backend.kanbantask')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
